// Barrel re-export — all original exports from courses.ts are now split across modules.
// This file preserves backward compatibility: `import { ... } from '@/lib/courses'` still works.

// Types
export type {
  ClassRow,
  Course,
  StudentProfile,
  Submission,
  Streak,
  Assignment,
  Resume,
  ResumeReview,
  ClosingReflection,
  BadgeProgress,
  Attendance,
  MySubmission,
  ResumeForGrading,
  WebhookConfig,
  StudentProgress,
  ServiceRecord,
  BadgeRow,
  Certificate,
  MiniTaskResponseRow,
  ModeratorProfile,
  ModeratorSchedule,
  MiniTask,
  MiniTaskResponse,
  MiniTaskResponseWithStudent,
  ModerationSupport,
  ModerationReport,
  Announcement,
  Quiz,
  QuizQuestion,
  QuizAttempt,
  MeditationVerse,
  WeeklyBilan,
  SoulTracking,
  SoulEntry,
  PaginatedResult,
} from './types'

// Course CRUD + media + file validation
export {
  COURSE_MEDIA_MAX_SIZE,
  ASSIGNMENT_FILE_MAX_SIZE,
  NOTE_FILE_MAX_SIZE,
  RESUME_FILE_MAX_SIZE,
  isCourseMediaFile,
  isAssignmentFile,
  isNoteImageFile,
  isResumeFile,
  getClasses,
  getCourses,
  getStudentCourse,
  getCurrentWeekForClass,
  uploadCourseFile,
  courseFileUrl,
  createCourse,
  updateCourse,
  deleteCourse,
  getClassCourses,
  getFollowedCourses,
  getLandingAvatars,
  getWebhookConfig,
  saveWebhookConfig,
  uploadCourseAudio,
  deleteCourseAudio,
  setClassStartDate,
  generateCourseDates,
  uploadSupportFile,
  uploadAssignmentFile,
  uploadNoteFile,
  uploadResumeFile,
  deleteResumeFile,
} from './courseData'

// User/moderator management
export {
  getStudents,
  deleteStudent,
  advanceStudent,
  getModerators,
  setAccessActive,
  setMeditationGrade,
  setModeratorRole,
  getModeratorClasses,
  setModeratorClasses,
  getModeratorSchedules,
  addModeratorSchedule,
  deleteModeratorSchedule,
  adminCreateUser,
  assignAdminClassClass,
  removeAdminClassClass,
  getAdminClassClasses,
  setStudentClass,
  getStudentsPaginated,
  searchProfiles,
} from './adminUsers'

// Announcements + reminders + verses
export {
  getAnnouncements,
  createAnnouncement,
  createBroadcastAnnouncement,
  deleteAnnouncement,
  updateAnnouncement,
  sendSaturdayReminders,
  getDailyVerse,
  getClassVerses,
  addVerse,
  removeVerse,
  toggleVerseActive,
  setVerseDay,
} from './announcements'

// Submissions + grading + resumes
export {
  getSubmissions,
  getAssignments,
  submitAssignment,
  submitNotes,
  getMySubmissions,
  getSubmissionsForGrading,
  gradeSubmission,
  getResume,
  saveResume,
  getResumesForReview,
  getResumesForGrading,
  gradeResume,
  getAllResumes,
  getClosingReflections,
  saveClosingReflection,
} from './submissions'

// Gamification: XP, badges, progress, attendance, streaks, bilan, service, mini-tasks, mod notes
export {
  getBadgeProgress,
  getBadges,
  ensureBadges,
  getAllBadges,
  getCertificates,
  getAttendances,
  markCourseAttendance,
  getStreaks,
  getStudentStreak,
  getStudentProgress,
  getServiceRecord,
  upsertServiceRecord,
  getAllMiniTaskResponses,
  getMiniTask,
  getMiniTasksAll,
  saveMiniTask,
  getMiniTaskResponse,
  saveMiniTaskResponse,
  getMiniTaskResponses,
  getWeeklyBilan,
  saveWeeklyBilan,
  getAllBilansForWeek,
  getBilanPreferences,
  saveBilanPreferences,
  getModNotes,
  saveModNotes,
  awardXp,
} from './gamification'

// Soul tracking + moderation reports
export {
  getSoulTracking,
  upsertSoulTracking,
  getSoulEntries,
  addSoulEntry,
  createModerationReport,
  getModerationReports,
  deleteModerationReport,
  getModerationSupport,
  getSupportsAll,
  saveModerationSupport,
} from './soulTracking'

// Quizzes
export {
  getCourseQuizzes,
  getQuizWithQuestions,
  startQuiz,
  submitQuiz,
  createQuiz,
  deleteQuiz,
} from './quizzes'

// Notifications
export {
  getNotifications,
  markNotificationsRead,
} from './notifications'
